spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dulminkannangara/testPublicConfig
          search-paths:
            - '*server'
#          username:
#          password:
#  For a private repo, u need to add username and password / token

  application:
    name: CONFIG_SERVER

#Port number
server:
  port: 8084

