spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dulminkannangara/testPublicConfig
          search-paths:
            - '*service'
          username: dulminkannangara
          password:

  application:
    name: CONFIG_SERVER

#Port number
server:
  port: 8084

