server:
  port: 8888

spring:
  application:
    name: gateway
  cloud:
    discovery:
      locator:
        lower-case-service-id: true
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8083/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false
